### ISSUE TITLE
carlaviz pull failed

### ISSUE THREAD

**Issue by bobd988** [SelfDriveGuard/sdg-engine#1]
1. 
This command failed to pull image from docker.io, where there is no tag for this image. For  other images I changed to use tag v1.0 and pull ok, but this image is not.  I suggest you put a example tag like v1.0 or just :latest to get things steps easier.

# 启动carlaviz
docker run -it --network="host" -e CARLAVIZ_HOST_IP=localhost -e CARLA_SERVER_IP=localhost -e CARLA_SERVER_PORT=2000 selfdriveguard/carlaviz

2. To fix above issue I use the mjxu96/carlaviz:latest to pull image.  Image pulled ok. Next I started carla-autoware ok, then opened http://localhost:8090. The page can be opened but server drop down is empty.  Using default value and clicking run a login pops up.  I suggest you put FAQ for trouble shooting.

**Comment by YunyunZhai** [comment]
it is ok now
